import { AppProps } from 'next/app';
import { ThemeProvider, createTheme } from '@mui/material/styles';
import { CssBaseline } from '@mui/material/';

const darkTheme = createTheme({
  palette: {
    mode: 'dark',
  },
});
export default function MyApp({ Component, pageProps }: AppProps) {


  return (<ThemeProvider theme={darkTheme}>
    <title>Dashboard</title>
    <meta name="description" content="Generated by create next app" />
    <meta charSet="utf-8" />
    <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"
    />
    <meta name="description" content="Description" />
    <meta name="keywords" content="Keywords" />
    <link rel="icon" href="/favicon.ico" />
    <CssBaseline />

    <main><Component {...pageProps} /></main>
  </ThemeProvider>
  )
}