import { AppProps } from 'next/app';
import '../styles/globals.css'

export default function MyApp({ Component, pageProps }: AppProps) {

  return (
    <main>
      <title>Dashboard</title>
      <meta name="description" content="Generated by create next app" />
      <meta charSet="utf-8" />
      <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
      <meta
        name="viewport"
        content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=5,user-scalable=yes "
      />
      <meta name="description" content="Description" />
      <meta name="keywords" content="Keywords" />
      <link rel="icon" href="/favicon.ico" />
      <Component {...pageProps} /></main>
  )
}