import { Grommet } from 'grommet'
import type { NextPage } from 'next'
import Head from 'next/head'
import AppGrid from '../components/AppGrid/AppGrid'
import SearchBar from '../components/SearchBar/SearchBar'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Grommet>        {SearchBar()}
          {AppGrid()}</Grommet>

      </main>
    </div>
  )
}

export default Home

let Sonarr= {
  appname : 'sonarr',
  appurl : 'https://sonarr.jbpixel.xyz',
  appdescription : 'This is the sonarr app for shows',
  apptype : 'app'
}