import { Container } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import AppGrid from '../components/AppGrid/AppGrid'
import SearchBar from '../components/SearchBar/SearchBar'
import Image from 'next/image'
import { useState } from 'react'
import style from '../styles/Home.module.css'

const styles = {
  paperContainer: {
      backgroundImage: `url(${'https://images.unsplash.com/photo-1654721661424-0d3df2b042db?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2264&q=80'})`
  }
};


const Home: NextPage = () => {

  return (
    <div>

      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Container  style={styles.paperContainer} className={style.Container}>
          {SearchBar()}
          {AppGrid()}

        </Container>
              
    </div>
  )
}

export default Home
